- ACHDictionary.go
- ACHDictionary_test.go
- go.mod
> Routing number search

- LICENSE
- WIREDictionary_test.go
> Add license 1

- README.md
- docs/FedACHdir.md
> Add badges to readme

- .codecov.yml
- .travis.yml
- ACHDictionary.go
- ACHDictionary_test.go
- CHANGELOG.md
- WIREDictionary.go
- WIREDictionary_test.go
- fileErrors.go
- version.go
> Update .yml files

- .travis.yml
- ACHDictionary.go
- ACHDictionary_test.go
- WIREDictionary.go
- WIREDictionary_test.go
Closes # 5
This seems to have been blown away, so I'm re-adding it
> Financial institution search redux

- ACHDictionary.go
- ACHDictionary_test.go
- WIREDictionary_test.go
- fileErrors.go
- validators.go
> 2 digit routing number search

- .travis.yml
- ACHDictionary.go
- ACHDictionary_test.go
- README.md
- WIREDictionary.go
- WIREDictionary_test.go
- const.go
- fileErrors.go
> Wire directory search

- .travis.yml
- ACHDictionary.go
- ACHDictionary_test.go
- openapi.yaml
This is a WIP for search endpoints
> WIP cmd/server mock out endpoints

- .travis.yml
- cmd/server/main.go
- cmd/server/search_handlers.go
- openapi.yaml
> Openapi.yaml

- README.md
See also https://github.com/moov-io/ach/pull/541
> docs: add more of a description for this project and mention relation to paygate

- client/api/openapi.yaml
- client/docs/AchParticipant.md
- client/docs/WireParticipant.md
- client/model_ach_participant.go
- client/model_wire_participant.go
- go.sum
- openapi.yaml
AchLocation isn't a list so changing the participant model so it can JSON unmarshal correctly
> changing ach and wire participant models as *Location isn't a list

- .travis.yml
- Dockerfile
See: https://golang.org/doc/go1.13
> build: upgrade to Go 1.13 and Debian 10

- client/api/openapi.yaml
- client/api_fed.go
- client/docs/FEDApi.md
- cmd/server/search_handlers.go
- cmd/server/search_handlers_test.go
- openapi.yaml
Issue: https://github.com/moov-io/fed/issues/69
> cmd/server: log x-request-id and x-user-id HTTP headers

- .travis.yml
- makefile
Fixes: https://github.com/moov-io/fed/issues/90
> build: release windows binary

- ACHDictionary_test.go
- WIREDictionary.go
- WIREDictionary_test.go
- cmd/server/reader.go
- cmd/server/search_test.go
- data/fpddir.json
The Fed has a JSON file we can read from also. 
See https://github.com/moov-io/fed/pull/89 for the ACH PR.
> wire: read official JSON data files

- Dockerfile
Update default image ports to match application defaults of 8086/9096
> Update Default Ports In DockerFile

- README.md
- openapi.yaml
- Added a header, table of contents, related projects, contributing section, and resources section
- Added a Google Cloud setup tutorial
- Miscellaneous minor changes
- Copied API docs .yaml file from 'api' directory into main directory
> docs: Improve readme with new sections and fixes

- README.md
- docs/README.md
Fixed a few things I missed during my initial readme update, as well as typos and formatting issues in other docs.
> Minor improvements to docs

- README.md
- docs/FedACHdir.md
- docs/README.md
- docs/fpddir.md
We briefly mention data is outdated in the two readmes, but we should go into more detail. This also cleans up the two data directories.
(Requested by Wade in Slack - https://moov-io.slack.com/archives/CD9J8EJKX/p1612476086055500)
> Clarify disclaimer for outdated data and sources

- docs/index.md
Updates the cover image from a generic Moov graphic to Fed-branded one.
> Update cover image on docs site

- cmd/server/search.go
- cmd/server/search_handlers_test.go
Fixes: https://github.com/moov-io/fed/issues/182
> fix: remove achParticipants or wireParticipants from json responses

- .github/CODEOWNERS
Add @jasonbornsteinMOOV to codeowners to help maintain bot updates
> add Jason to codeowners

- ACHDictionary_test.go
- WIREDictionary_test.go
- cmd/server/reader.go
Context: https://moov-io.slack.com/archives/CUK2129G8/p1745842846489039
> cmd/server: fail on startup when zero participants are found

- web/search.html
- Implemented a web ui under web/search.html
- Technical stacks are html, css js
closes #146
> Implemented simple web-ui
